#:schema node_modules/wrangler/config-schema.json
name = "kontext-realtime"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"


[dev]
live_reload = true

[observability.logs]
enabled = true
